-- Real Welsh place names (towns, villages, cities). Format matches the base
-- game's names/england/en/towns.lua: a flat array of strings returned
-- directly, no procedural generation.
return {
	--large
	"Cardiff",
	"Swansea",
	"Newport",
	"Wrexham",
	"Merthyr Tydfil",
	"Bangor",

	--normal
	"Llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch",
	"Aberystwyth",
	"Caernarfon",
	"Llandudno",
	"Betws-y-Coed",
	"Porthmadog",
	"Pwllheli",
	"Blaenau Ffestiniog",
	"Machynlleth",
	"Dolgellau",
	"Barmouth",
	"Conwy",
	"Pontypridd",
	"Llanelli",
	"Aberdare",
	"Ystradgynlais",
	"Ebbw Vale",
	"Abergavenny",
	"Brecon",
	"Builth Wells",
	"Rhayader",
	"Presteigne",
	"Knighton",
	"Newtown",
	"Welshpool",
	"Llanidloes",
	"Tywyn",
	"Aberdyfi",
	"Fishguard",
	"Cardigan",
	"Lampeter",
	"Llandeilo",
	"Llandovery",
	"Ammanford",
	"Neath",
	"Bridgend",
	"Pontypool",
	"Tredegar",
	"Ystrad Mynach",
	"Caerphilly",
	"Chepstow",
	"Monmouth",
	"Tenby",
	"Pembroke",
	"Haverfordwest",
	"Milford Haven",
	"St Davids",
	"Narberth",
	"Holyhead",
	"Llangefni",
	"Amlwch",
	"Beaumaris",
	"Menai Bridge",
	"Llanberis",
	"Beddgelert",
	"Ruthin",
	"Denbigh",
	"Mold",
	"Flint",
	"Prestatyn",
	"Rhyl",
	"Colwyn Bay",
	"Llanrwst",
	"Corwen",
	"Bala",
	"Llangollen",
	"Aberaeron",
	"Porthcawl",
	"Barry",
	"Llantwit Major",
	"Cowbridge",
	"Llanfairfechan",

	--Talyllyn Railway (Tywyn to Nant Gwernol)
	"Pendre",
	"Hendy",
	"Fach Goch",
	"Cynfal",
	"Rhydyronen",
	"Tynllwynhen",
	"Brynglas",
	"Dolgoch",
	"Abergynolwyn",
	"Nant Gwernol",

	--Corris Railway (Machynlleth to Aberllefenni)
	"Corris",
	"Aberllefenni",
	"Maespoeth",
	"Derwenlas",
	"Morben",

	--Ffestiniog Railway (Porthmadog to Blaenau Ffestiniog)
	"Minffordd",
	"Penrhyn",
	"Tan-y-Bwlch",
	"Dduallt",
	"Tanygrisiau",

	--Welsh Highland Railway (Caernarfon to Porthmadog)
	"Dinas",
	"Waunfawr",
	"Rhyd Ddu",
	"Nantmor",
	"Pont Croesor",

	--lakes and rivers (concentrated around the same four heritage railways)
	"Llyn Mwyngil",
	"Afon Fathew",
	"Afon Dysynni",
	"Afon Dulas",
	"Afon Dyfi",
	"Afon Glaslyn",
	"Aberglaslyn",
	"Afon Dwyryd",
	"Traeth Mawr",
	"Llyn Cwellyn",
	"Llyn y Gadair",
	"Llyn Dinas",
	"Llyn Trawsfynydd",
}
