-- Real Welsh place names (towns, villages, cities). Format matches the base
-- game's names/england/en/towns.lua: a flat array of strings returned
-- directly, no procedural generation.
return {
	--large
	"Cardiff",
	"Swansea",
	"Newport",
	"Wrexham",
	"Merthyr Tydfil",
	"Bangor",

	--normal
	"Llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch",
	"Aberystwyth",
	"Caernarfon",
	"Llandudno",
	"Betws-y-Coed",
	"Porthmadog",
	"Pwllheli",
	"Blaenau Ffestiniog",
	"Machynlleth",
	"Dolgellau",
	"Barmouth",
	"Conwy",
	"Pontypridd",
	"Llanelli",
	"Aberdare",
	"Ystradgynlais",
	"Ebbw Vale",
	"Abergavenny",
	"Brecon",
	"Builth Wells",
	"Rhayader",
	"Presteigne",
	"Knighton",
	"Newtown",
	"Welshpool",
	"Llanidloes",
	"Tywyn",
	"Aberdyfi",
	"Fishguard",
	"Cardigan",
	"Lampeter",
	"Llandeilo",
	"Llandovery",
	"Ammanford",
	"Neath",
	"Bridgend",
	"Pontypool",
	"Tredegar",
	"Ystrad Mynach",
	"Caerphilly",
	"Chepstow",
	"Monmouth",
	"Tenby",
	"Pembroke",
	"Haverfordwest",
	"Milford Haven",
	"St Davids",
	"Narberth",
	"Holyhead",
	"Llangefni",
	"Amlwch",
	"Beaumaris",
	"Menai Bridge",
	"Llanberis",
	"Beddgelert",
	"Ruthin",
	"Denbigh",
	"Mold",
	"Flint",
	"Prestatyn",
	"Rhyl",
	"Colwyn Bay",
	"Llanrwst",
	"Corwen",
	"Bala",
	"Llangollen",
	"Aberaeron",
	"Porthcawl",
	"Barry",
	"Llantwit Major",
	"Cowbridge",
	"Llanfairfechan",

	--near Llandudno
	"Deganwy",
	"Llandudno Junction",
	"Penrhyn Bay",
	"Rhos-on-Sea",

	--near Llansteffan (Tywi/Taf estuary, Carmarthen Bay)
	"Llansteffan",
	"Ferryside",
	"Llangain",
	"Llanybri",
	"Llansaint",
	"Kidwelly",
	"Laugharne",
	"St Clears",
	"Carmarthen",
	"Pembrey",
	"Pendine",

	--Talyllyn Railway (Tywyn to Nant Gwernol)
	"Tywyn Wharf",
	"Pendre",
	"Hendy",
	"Fach Goch",
	"Cynfal",
	"Rhydyronen",
	"Tynllwynhen",
	"Brynglas",
	"Quarry Siding",
	"Dolgoch",
	"Abergynolwyn",
	"Nant Gwernol",

	--Corris Railway (Machynlleth to Aberllefenni)
	"Corris",
	"Aberllefenni",
	"Maespoeth",
	"Derwenlas",
	"Morben",
	"Ffridd Gate",
	"Llwyngwern",
	"Esgairgeiliog",
	"Garneddwen",

	--Ffestiniog Railway (Porthmadog to Blaenau Ffestiniog)
	"Porthmadog Harbour",
	"Boston Lodge",
	"Pen Cob",
	"Minffordd",
	"Pen y Bryn",
	"Penrhyn",
	"Rhiw Goch",
	"Plas Halt",
	"Tan-y-Bwlch",
	"Coed y Bleiddiau",
	"Campbell's Platform",
	"Dduallt",
	"Gelliwiog",
	"Llyn Ystradau",
	"Tanygrisiau",

	--Welsh Highland Railway (Caernarfon to Porthmadog)
	"Bontnewydd",
	"Dinas",
	"Tryfan Junction",
	"Waunfawr",
	"Plas-y-Nant",
	"Snowdon Ranger",
	"Rhyd Ddu",
	"Meillionen",
	"Nantmor",
	"Pont Croesor",

	--Great Orme Tramway (Llandudno)
	"Llandudno Victoria",
	"Halfway",
	"Summit",

	--lakes and rivers (concentrated around the same four heritage railways, plus Llansteffan/Llandudno)
	"Llyn Mwyngil",
	"Afon Fathew",
	"Afon Dysynni",
	"Afon Dulas",
	"Afon Dyfi",
	"Afon Glaslyn",
	"Aberglaslyn",
	"Afon Dwyryd",
	"Traeth Mawr",
	"Llyn Cwellyn",
	"Llyn y Gadair",
	"Llyn Dinas",
	"Llyn Trawsfynydd",
	"Afon Tywi",
	"Afon Taf",
	"Bae Caerfyrddin",
}
