-- Real Welsh place names (towns, villages, cities). Format matches the base
-- game's names/england/en/towns.lua: a flat array of strings returned
-- directly, no procedural generation.
return {
	--large
	"Cardiff",
	"Swansea",
	"Newport",
	"Wrexham",
	"Merthyr Tydfil",
	"Bangor",

	--normal
	"Llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch",
	"Aberystwyth",
	"Caernarfon",
	"Llandudno",
	"Betws-y-Coed",
	"Porthmadog",
	"Pwllheli",
	"Blaenau Ffestiniog",
	"Machynlleth",
	"Dolgellau",
	"Barmouth",
	"Conwy",
	"Pontypridd",
	"Llanelli",
	"Aberdare",
	"Ystradgynlais",
	"Ebbw Vale",
	"Abergavenny",
	"Brecon",
	"Builth Wells",
	"Rhayader",
	"Presteigne",
	"Knighton",
	"Newtown",
	"Welshpool",
	"Llanidloes",
	"Tywyn",
	"Aberdyfi",
	"Fishguard",
	"Cardigan",
	"Lampeter",
	"Llandeilo",
	"Llandovery",
	"Ammanford",
	"Neath",
	"Bridgend",
	"Pontypool",
	"Tredegar",
	"Ystrad Mynach",
	"Caerphilly",
	"Chepstow",
	"Monmouth",
	"Tenby",
	"Pembroke",
	"Haverfordwest",
	"Milford Haven",
	"St Davids",
	"Narberth",
	"Holyhead",
	"Llangefni",
	"Amlwch",
	"Beaumaris",
	"Menai Bridge",
	"Llanberis",
	"Beddgelert",
	"Ruthin",
	"Denbigh",
	"Mold",
	"Flint",
	"Prestatyn",
	"Rhyl",
	"Colwyn Bay",
	"Llanrwst",
	"Corwen",
	"Bala",
	"Llangollen",
	"Aberaeron",
	"Porthcawl",
	"Barry",
	"Llantwit Major",
	"Cowbridge",
	"Llanfairfechan",
}
