-- Real Welsh street names, using authentic Welsh road-name vocabulary
-- (Stryd/Heol/Ffordd = street/road, Lôn = lane, Rhodfa = avenue,
-- Maes = green/field/square, Bryn = hill, Cae = field, Glan = bank/shore,
-- Llys = court, Parc = park, Ffynnon = well/spring). Format matches the
-- base game's names/england/en/streets.lua: a flat array of strings.
return {
	"Stryd Fawr",
	"Heol Fawr",
	"Heol y Bont",
	"Heol yr Eglwys",
	"Heol Newydd",
	"Heol Wen",
	"Heol Dinbych",
	"Heol y Castell",
	"Ffordd y Môr",
	"Ffordd Newydd",
	"Ffordd Bangor",
	"Ffordd Caernarfon",
	"Lôn Isaf",
	"Lôn Uchaf",
	"Lôn Fach",
	"Maes-y-Dref",
	"Maes-y-Llan",
	"Maes-y-Coed",
	"Maes Alun",
	"Bryn Awelon",
	"Bryn-y-Môr",
	"Bryn Teg",
	"Cae'r Ysgol",
	"Cae Mawr",
	"Rhodfa'r Môr",
	"Rhodfa'r Tywod",
	"Glan-y-Môr",
	"Glan-yr-Afon",
	"Ffynnon Wen",
	"Parc-y-Rhos",
	"Llys-y-Coed",
	"Stryd y Farchnad",
}
