-- Welsh street names, using authentic Welsh road-name vocabulary
-- (Stryd/Heol/Ffordd = street/road, Lôn = lane, Rhodfa = avenue,
-- Maes = green/field/square, Bryn = hill, Cae = field, Glan = bank/shore,
-- Llys = court, Parc = park, Ffynnon = well/spring, Teras = terrace,
-- Cilgant = crescent, Clos = close, Rhes = row). Format matches the base
-- game's names/england/en/streets.lua: a flat array of strings.
return {
	--Stryd (street)
	"Stryd Fawr",
	"Stryd Fach",
	"Stryd y Farchnad",
	"Stryd yr Eglwys",
	"Stryd y Capel",
	"Stryd y Castell",
	"Stryd y Bont",
	"Stryd y Llyn",
	"Stryd y Dŵr",
	"Stryd y Felin",
	"Stryd yr Orsaf",
	"Stryd y Porth",
	"Stryd y Plas",
	"Stryd Newydd",
	"Stryd Wesla",
	"Stryd Fictoria",
	"Stryd y Dderwen",
	"Stryd Penlan",
	"Stryd Glyndŵr",
	"Stryd Llywelyn",
	"Stryd Madog",
	"Stryd Dewi Sant",

	--Heol (road)
	"Heol Fawr",
	"Heol y Bont",
	"Heol yr Eglwys",
	"Heol y Capel",
	"Heol Newydd",
	"Heol Wen",
	"Heol Dinbych",
	"Heol y Castell",
	"Heol y Felin",
	"Heol yr Orsaf",
	"Heol y Parc",
	"Heol y Coed",
	"Heol y Mynydd",
	"Heol y Cwm",
	"Heol y Waun",
	"Heol yr Ysgol",
	"Heol y Gaer",
	"Heol Llanelli",
	"Heol Caerfyrddin",
	"Heol Aberhonddu",
	"Heol Abertawe",
	"Heol Penybont",
	"Heol Hir",
	"Heol Isaf",
	"Heol Uchaf",
	"Heol Hendre",
	"Heol Tregwilym",
	"Heol y Gwynt",
	"Heol Gwyndaf",
	"Heol Islwyn",

	--Ffordd (way/road)
	"Ffordd y Môr",
	"Ffordd Newydd",
	"Ffordd Bangor",
	"Ffordd Caernarfon",
	"Ffordd Conwy",
	"Ffordd Pwllheli",
	"Ffordd Penrhos",
	"Ffordd yr Orsaf",
	"Ffordd y Traeth",
	"Ffordd y Llan",
	"Ffordd Eryri",
	"Ffordd Glasfryn",
	"Ffordd Tan-y-Bryn",
	"Ffordd Cadnant",
	"Ffordd Garth",
	"Ffordd Coed Mawr",
	"Ffordd Gwynedd",
	"Ffordd Penlan",
	"Ffordd Clwyd",
	"Ffordd Ffestiniog",

	--Lôn (lane)
	"Lôn Isaf",
	"Lôn Uchaf",
	"Lôn Fach",
	"Lôn Goed",
	"Lôn Las",
	"Lôn Gwyrfai",
	"Lôn Eithin",
	"Lôn y Wern",
	"Lôn y Felin",
	"Lôn Ddu",
	"Lôn Bach",
	"Lôn Cefn",
	"Lôn Pen-y-Ffridd",
	"Lôn Ty'n Rhos",
	"Lôn Tyddyn",

	--Rhodfa (avenue/promenade)
	"Rhodfa'r Môr",
	"Rhodfa'r Tywod",
	"Rhodfa'r Gorllewin",
	"Rhodfa'r Dwyrain",
	"Rhodfa Fadog",
	"Rhodfa Glyndŵr",
	"Rhodfa'r Parc",

	--Maes (field/square)
	"Maes-y-Dref",
	"Maes-y-Llan",
	"Maes-y-Coed",
	"Maes Alun",
	"Maes yr Haf",
	"Maes Glas",
	"Maes Hyfryd",
	"Maes Gwyn",
	"Maes-y-Delyn",
	"Maes-y-Dderwen",
	"Maes Ifor",
	"Maes Mawr",
	"Maes y Ffynnon",
	"Maes Meurig",

	--Bryn (hill)
	"Bryn Awelon",
	"Bryn-y-Môr",
	"Bryn Teg",
	"Bryn Glas",
	"Bryn Hyfryd",
	"Bryn Eithin",
	"Bryn Coed",
	"Bryn Gwyn",
	"Bryn Derw",
	"Bryn Mawr",
	"Bryn Seion",
	"Bryn Tirion",
	"Bryn-y-Gog",
	"Bryn Llwyd",

	--Cae (field)
	"Cae'r Ysgol",
	"Cae Mawr",
	"Cae Bach",
	"Cae Glas",
	"Cae Coch",
	"Cae Gwyn",
	"Cae Hen",
	"Cae'r Felin",
	"Cae'r Delyn",
	"Cae Main",

	--Glan (bank/shore)
	"Glan-y-Môr",
	"Glan-yr-Afon",
	"Glan-y-Don",
	"Glan Llyn",
	"Glan Conwy",
	"Glan-y-Werydd",
	"Glan Rhyd",

	--Ffynnon (well/spring)
	"Ffynnon Wen",
	"Ffynnon Las",
	"Ffynnon Fair",
	"Ffynnon Dewi",

	--Parc (park)
	"Parc-y-Rhos",
	"Parc Gwyn",
	"Parc Bryn",
	"Parc Menai",
	"Parc Hendre",

	--Llys (court)
	"Llys-y-Coed",
	"Llys Glas",
	"Llys Gwynedd",
	"Llys Owain",
	"Llys Branwen",
	"Llys Hywel",
	"Llys Dafydd",

	--Teras (terrace) and Rhes (row)
	"Teras y Capel",
	"Teras Bryn",
	"Teras Fictoria",
	"Teras y Rheilffordd",
	"Teras Glanrafon",
	"Teras Gwynfryn",
	"Teras Penrhyn",
	"Rhes y Felin",
	"Rhes yr Ysgol",
	"Rhes Newydd",

	--Cilgant (crescent) and Clos (close)
	"Cilgant y Lili",
	"Cilgant Glanmor",
	"Cilgant y Bryn",
	"Clos y Wern",
	"Clos Tŷ Gwyn",
	"Clos Llwyn",
	"Clos y Cwm",
	"Clos Afallon",

	--Other common street names
	"Y Stryd",
	"Y Maes",
	"Y Wern",
	"Y Gilfach",
	"Penrallt",
	"Penlan",
	"Pen-y-Bryn",
	"Pen-y-Groes",
	"Pen-y-Cae",
	"Pen-y-Ffordd",
	"Tan-y-Bryn",
	"Tan-y-Fron",
	"Tan-y-Graig",
	"Tŷ Newydd",
	"Tŷ Gwyn",
	"Erw Wen",
	"Erw Las",
	"Gerddi'r Afon",
	"Gwel-y-Môr",
	"Gwel Eryri",
	"Ael-y-Bryn",
	"Coed y Glyn",
	"Allt Goch",
	"Allt-yr-Ynn",
	"Cwrt y Plas",
	"Llwyn Onn",
	"Llwyn Derw",
	"Min-y-Nant",
	"Nant y Felin",
	"Dôl Werdd",
	"Dolafon",
}
