-- Real Welsh place names (cities, towns and villages). Format matches the base
-- game's names/england/en/towns.lua: a flat array of strings returned
-- directly, no procedural generation.
return {
	--large
	"Cardiff",
	"Swansea",
	"Newport",
	"Wrexham",
	"Merthyr Tydfil",
	"Bangor",
	"St Asaph",
	"St Davids",
	"Barry",
	"Neath",
	"Bridgend",
	"Llanelli",
	"Port Talbot",
	"Cwmbran",
	"Caerphilly",
	"Pontypridd",
	"Rhondda",
	"Aberdare",
	"Carmarthen",
	"Aberystwyth",

	--normal
	"Llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch",

	--around the heritage railways (Talyllyn, Corris, Ffestiniog, Welsh
	--Highland); the towns at either end are in their regions below
	"Pendre",
	"Dolgoch",
	"Brynglas",
	"Tal-y-llyn",
	"Llanfihangel-y-Pennant",
	"Maespoeth",
	"Llwyngwern",
	"Garneddwen",
	"Tan-y-Bwlch",
	"Dduallt",
	"Boston Lodge",
	"Plas-y-Nant",
	"Pont Croesor",

	--North West: Anglesey, Gwynedd
	"Caernarfon",
	"Porthmadog",
	"Pwllheli",
	"Criccieth",
	"Blaenau Ffestiniog",
	"Ffestiniog",
	"Penrhyndeudraeth",
	"Harlech",
	"Barmouth",
	"Dolgellau",
	"Bala",
	"Tywyn",
	"Aberdyfi",
	"Abergynolwyn",
	"Rhydyronen",
	"Bryncrug",
	"Llwyngwril",
	"Fairbourne",
	"Arthog",
	"Llanbedr",
	"Dyffryn Ardudwy",
	"Talsarnau",
	"Trawsfynydd",
	"Llan Ffestiniog",
	"Maentwrog",
	"Tanygrisiau",
	"Minffordd",
	"Tremadog",
	"Prenteg",
	"Garndolbenmaen",
	"Llanystumdwy",
	"Chwilog",
	"Abersoch",
	"Llanbedrog",
	"Aberdaron",
	"Nefyn",
	"Morfa Nefyn",
	"Tudweiliog",
	"Botwnnog",
	"Llithfaen",
	"Trefor",
	"Clynnog Fawr",
	"Llanaelhaearn",
	"Penygroes",
	"Talysarn",
	"Nantlle",
	"Groeslon",
	"Llanwnda",
	"Bontnewydd",
	"Dinas",
	"Waunfawr",
	"Betws Garmon",
	"Rhyd Ddu",
	"Beddgelert",
	"Nantmor",
	"Llanfrothen",
	"Croesor",
	"Llanberis",
	"Nant Peris",
	"Llanrug",
	"Cwm-y-Glo",
	"Deiniolen",
	"Penisa'r Waun",
	"Bethel",
	"Y Felinheli",
	"Bethesda",
	"Tregarth",
	"Llandygai",
	"Rachub",
	"Llanllechid",
	"Abergwyngregyn",
	"Llanfairfechan",
	"Penmaenmawr",
	"Rhosgadfan",
	"Rhostryfan",
	"Carmel",
	"Llanllyfni",
	"Pant Glas",
	"Brynsiencyn",
	"Holyhead",
	"Llangefni",
	"Amlwch",
	"Beaumaris",
	"Menai Bridge",
	"Benllech",
	"Moelfre",
	"Cemaes",
	"Llanerchymedd",
	"Rhosneigr",
	"Aberffraw",
	"Newborough",
	"Malltraeth",
	"Bodedern",
	"Valley",
	"Trearddur Bay",
	"Rhoscolyn",
	"Gwalchmai",
	"Llanfaethlu",
	"Llanddona",
	"Pentraeth",
	"Llangoed",
	"Llandegfan",
	"Gaerwen",
	"Dwyran",
	"Bodorgan",
	"Llanfachraeth",
	"Llanddaniel Fab",
	"Penmynydd",

	--North East: Conwy, Denbighshire, Flintshire, Wrexham
	"Conwy",
	"Llandudno",
	"Llandudno Junction",
	"Deganwy",
	"Penrhyn Bay",
	"Rhos-on-Sea",
	"Colwyn Bay",
	"Old Colwyn",
	"Llanddulas",
	"Abergele",
	"Towyn",
	"Kinmel Bay",
	"Betws-y-Coed",
	"Llanrwst",
	"Trefriw",
	"Dolgarrog",
	"Tal-y-Bont",
	"Rowen",
	"Capel Curig",
	"Dolwyddelan",
	"Penmachno",
	"Ysbyty Ifan",
	"Pentrefoelas",
	"Cerrigydrudion",
	"Llansannan",
	"Llanfair Talhaiarn",
	"Llangernyw",
	"Eglwysbach",
	"Glan Conwy",
	"Llysfaen",
	"Rhyl",
	"Prestatyn",
	"Rhuddlan",
	"Dyserth",
	"Meliden",
	"Gronant",
	"Trefnant",
	"Bodelwyddan",
	"Denbigh",
	"Ruthin",
	"Llanfair Dyffryn Clwyd",
	"Llandyrnog",
	"Llanbedr Dyffryn Clwyd",
	"Bodfari",
	"Henllan",
	"Llanrhaeadr",
	"Clawddnewydd",
	"Gwyddelwern",
	"Corwen",
	"Cynwyd",
	"Llandrillo",
	"Carrog",
	"Glyndyfrdwy",
	"Llangollen",
	"Trevor",
	"Froncysyllte",
	"Chirk",
	"Glyn Ceiriog",
	"Llanarmon Dyffryn Ceiriog",
	"Mold",
	"Flint",
	"Holywell",
	"Buckley",
	"Connah's Quay",
	"Shotton",
	"Queensferry",
	"Hawarden",
	"Saltney",
	"Broughton",
	"Penyffordd",
	"Caergwrle",
	"Hope",
	"Treuddyn",
	"Llanarmon-yn-Iâl",
	"Cilcain",
	"Nannerch",
	"Caerwys",
	"Ysceifiog",
	"Whitford",
	"Mostyn",
	"Ffynnongroyw",
	"Talacre",
	"Bagillt",
	"Halkyn",
	"Northop",
	"Mynydd Isa",
	"Gwernymynydd",
	"Rhosllanerchrugog",
	"Ruabon",
	"Cefn Mawr",
	"Acrefair",
	"Coedpoeth",
	"Brymbo",
	"Gwersyllt",
	"Rhosrobin",
	"Llay",
	"Gresford",
	"Rossett",
	"Marford",
	"Holt",
	"Bangor-on-Dee",
	"Overton",
	"Penley",
	"Johnstown",
	"Penycae",

	--Mid Wales: Powys, Ceredigion
	"Machynlleth",
	"Corris",
	"Aberllefenni",
	"Esgairgeiliog",
	"Derwenlas",
	"Pennal",
	"Cemmaes Road",
	"Cemmaes",
	"Llanbrynmair",
	"Carno",
	"Caersws",
	"Llandinam",
	"Llanidloes",
	"Trefeglwys",
	"Staylittle",
	"Newtown",
	"Tregynon",
	"Kerry",
	"Abermule",
	"Montgomery",
	"Churchstoke",
	"Welshpool",
	"Llanfair Caereinion",
	"Llanfyllin",
	"Llansantffraid-ym-Mechain",
	"Meifod",
	"Guilsfield",
	"Berriew",
	"Four Crosses",
	"Llanymynech",
	"Llanrhaeadr-ym-Mochnant",
	"Llangynog",
	"Llanwddyn",
	"Llangadfan",
	"Dinas Mawddwy",
	"Mallwyd",
	"Rhayader",
	"Llanwrthwl",
	"Elan Village",
	"Llandrindod Wells",
	"Builth Wells",
	"Llanwrtyd Wells",
	"Beulah",
	"Llangammarch Wells",
	"Newbridge-on-Wye",
	"Erwood",
	"Hay-on-Wye",
	"Talgarth",
	"Bronllys",
	"Brecon",
	"Llanfaes",
	"Sennybridge",
	"Defynnog",
	"Trecastle",
	"Crickhowell",
	"Llangynidr",
	"Llangattock",
	"Bwlch",
	"Llangors",
	"Ystradgynlais",
	"Ystradfellte",
	"Penderyn",
	"Knighton",
	"Presteigne",
	"Knucklas",
	"Llanbister",
	"Llananno",
	"New Radnor",
	"Old Radnor",
	"Painscastle",
	"Gladestry",
	"Aberaeron",
	"New Quay",
	"Llanarth",
	"Cardigan",
	"Aberporth",
	"Tresaith",
	"Llangrannog",
	"Penbryn",
	"Llandysul",
	"Newcastle Emlyn",
	"Adpar",
	"Lampeter",
	"Llanybydder",
	"Tregaron",
	"Pontrhydfendigaid",
	"Ysbyty Ystwyth",
	"Devil's Bridge",
	"Ponterwyd",
	"Capel Bangor",
	"Bow Street",
	"Borth",
	"Talybont",
	"Tre'r-ddôl",
	"Llanon",
	"Llanrhystud",
	"Llanilar",
	"Llanfarian",
	"Penparcau",
	"Llanbadarn Fawr",
	"Felinfach",
	"Ciliau Aeron",
	"Talgarreg",
	"Synod Inn",
	"Llanwnnen",
	"Cribyn",

	--South West: Pembrokeshire, Carmarthenshire
	"Haverfordwest",
	"Pembroke",
	"Pembroke Dock",
	"Milford Haven",
	"Neyland",
	"Tenby",
	"Saundersfoot",
	"Narberth",
	"Fishguard",
	"Goodwick",
	"Trefdraeth",
	"Dinas Cross",
	"Crymych",
	"Maenclochog",
	"Letterston",
	"Solva",
	"Newgale",
	"Little Haven",
	"Broad Haven",
	"Dale",
	"Marloes",
	"Herbrandston",
	"Johnston",
	"Manorbier",
	"Lamphey",
	"Angle",
	"Freystrop",
	"Kilgetty",
	"Amroth",
	"Clynderwen",
	"Llandissilio",
	"Wiston",
	"Mathry",
	"Trefin",
	"Porthgain",
	"Abereiddy",
	"Croesgoch",
	"St Dogmaels",
	"Cilgerran",
	"Boncath",
	"Eglwyswrw",
	"Llansteffan",
	"Ferryside",
	"Llangain",
	"Llanybri",
	"Llansaint",
	"Kidwelly",
	"Laugharne",
	"St Clears",
	"Pendine",
	"Pembrey",
	"Burry Port",
	"Trimsaran",
	"Pontyates",
	"Pontyberem",
	"Cross Hands",
	"Tumble",
	"Gorslas",
	"Llannon",
	"Pontarddulais",
	"Hendy",
	"Llangennech",
	"Bynea",
	"Dafen",
	"Felinfoel",
	"Llwynhendy",
	"Ammanford",
	"Glanaman",
	"Garnant",
	"Brynamman",
	"Tycroes",
	"Saron",
	"Llandybie",
	"Llandeilo",
	"Ffairfach",
	"Llangadog",
	"Llandovery",
	"Myddfai",
	"Cilycwm",
	"Rhandirmwyn",
	"Llansawel",
	"Talley",
	"Llanwrda",
	"Pumsaint",
	"Llansadwrn",
	"Llanarthne",
	"Nantgaredig",
	"Llanegwad",
	"Abergwili",
	"Peniel",
	"Cynwyl Elfed",
	"Llanpumsaint",
	"Brechfa",
	"Llanfynydd",
	"Whitland",
	"Llanboidy",
	"Meidrim",
	"Trelech",
	"Newchurch",
	"Bronwydd",
	"Pencader",
	"Llanllwni",
	"Drefach Felindre",
	"Llangeler",

	--South: Swansea, Neath Port Talbot, Glamorgan
	"Gorseinon",
	"Pontlliw",
	"Clydach",
	"Morriston",
	"Ystalyfera",
	"Pontardawe",
	"Gwaun-Cae-Gurwen",
	"Cwmllynfell",
	"Mumbles",
	"Oystermouth",
	"Killay",
	"Sketty",
	"Gowerton",
	"Penclawdd",
	"Llanrhidian",
	"Reynoldston",
	"Port Eynon",
	"Rhossili",
	"Llangennith",
	"Bishopston",
	"Pennard",
	"Skewen",
	"Briton Ferry",
	"Baglan",
	"Cwmafan",
	"Pontrhydyfen",
	"Glyncorrwg",
	"Cymmer",
	"Resolven",
	"Glynneath",
	"Seven Sisters",
	"Crynant",
	"Cadoxton",
	"Tonna",
	"Aberdulais",
	"Maesteg",
	"Caerau",
	"Nantyffyllon",
	"Ogmore Vale",
	"Nant-y-moel",
	"Pontycymer",
	"Blaengarw",
	"Pencoed",
	"Porthcawl",
	"Kenfig Hill",
	"Pyle",
	"Cornelly",
	"Ewenny",
	"Llantwit Major",
	"Cowbridge",
	"Llanblethian",
	"St Athan",
	"Rhoose",
	"Llantwit Fardre",
	"Penarth",
	"Dinas Powys",
	"Sully",
	"Wenvoe",
	"Peterston-super-Ely",
	"St Fagans",
	"Llandaff",
	"Radyr",
	"Whitchurch",
	"Llanishen",
	"Rhiwbina",
	"Tongwynlais",
	"Taff's Well",
	"Llantrisant",
	"Pontyclun",
	"Talbot Green",
	"Llanharan",
	"Llanharry",
	"Tonyrefail",
	"Gilfach Goch",
	"Porth",
	"Tonypandy",
	"Treorchy",
	"Treherbert",
	"Pentre",
	"Ton Pentre",
	"Ystrad",
	"Llwynypia",
	"Ferndale",
	"Tylorstown",
	"Maerdy",
	"Mountain Ash",
	"Abercynon",
	"Ynysybwl",
	"Cilfynydd",
	"Treforest",
	"Hirwaun",
	"Aberaman",
	"Cwmbach",
	"Abercwmboi",
	"Troedyrhiw",
	"Aberfan",
	"Merthyr Vale",
	"Treharris",
	"Trelewis",
	"Dowlais",
	"Pant",

	--South East: the Valleys, Monmouthshire
	"Ystrad Mynach",
	"Bargoed",
	"Aberbargoed",
	"Blackwood",
	"Pengam",
	"Fleur-de-Lys",
	"Newbridge",
	"Crumlin",
	"Abercarn",
	"Risca",
	"Crosskeys",
	"Ynysddu",
	"Wattsville",
	"Bedwas",
	"Machen",
	"Trethomas",
	"Nelson",
	"Senghenydd",
	"Abertridwr",
	"Llanbradach",
	"Gelligaer",
	"Rhymney",
	"New Tredegar",
	"Tredegar",
	"Ebbw Vale",
	"Brynmawr",
	"Nantyglo",
	"Blaina",
	"Abertillery",
	"Six Bells",
	"Cwm",
	"Llanhilleth",
	"Abersychan",
	"Blaenavon",
	"Pontypool",
	"Griffithstown",
	"Pontnewydd",
	"Croesyceiliog",
	"Caerleon",
	"Ponthir",
	"Bassaleg",
	"Rogerstone",
	"Marshfield",
	"St Brides Wentloog",
	"Langstone",
	"Llanwern",
	"Magor",
	"Undy",
	"Caldicot",
	"Portskewett",
	"Caerwent",
	"Chepstow",
	"Tintern",
	"Trellech",
	"Monmouth",
	"Raglan",
	"Usk",
	"Llanbadoc",
	"Abergavenny",
	"Llanfoist",
	"Govilon",
	"Gilwern",
	"Llanover",
	"Llanvihangel Crucorney",
	"Llanthony",
	"Skenfrith",
	"Grosmont",
	"Llantilio Crossenny",
	"Penperlleni",
	"Shirenewton",
}
